### PR TITLE
Fix 24418

### LINKED ISSUE #24418: Imported segmented track invisible until list is refreshed
### Description

The bug appears only when you import a multi-segment GPX file as separate tracks

### Steps to reproduce

When importing a multi-segment track, choose to import as separate segments `Import 18/18` button (for example)

### Actual result

Tracks (folder with tracks) is displayed after refreshing the page

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/ad2a7a74-8ef8-4fd5-b19a-a0b7ec79bf3e"></video>
</details>

### Expected result

- [ ] Tracks are displayed immediately after import (as in the case when all segments are imported as a single track).

<details><summary>Details</summary>
<video src="https://github.com/user-attachments/assets/2950be5b-570a-4081-af83-0d8c8071e6a4"></video>
</details> 

### Your Environment
OsmAnd Version: OsmAnd~ 5.3.0#7108m, Released: 2026-02-05
Android/iOS version: 12

### PR DESCRIPTION
**Pull request by 0xRe1nk0**

### CODE REVIEW

File: OsmAnd/src/net/osmand/plus/importfiles/tasks/SaveTracksTask.java [hunk 1]
```diff
@@ -69,6 +70,17 @@ protected List<String> doInBackground(Void... params) {
...
 	}
 
+	private void processSavedFile(@NonNull File file, @NonNull GpxFile gpxFile) {
+		gpxFile.setPath(file.getAbsolutePath());
+
+		KFile kFile = SharedUtil.kFile(file);
+		GpxDataItem item = new GpxDataItem(kFile);
+		item.readGpxParams(gpxFile);
+		app.getGpxDbHelper().remove(kFile);
+		app.getGpxDbHelper().add(item);
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/importfiles/tasks/SaveTracksTask.java]: Should we use updateDataItem or add gpxDbHelper.replace()?

File: OsmAnd/src/net/osmand/plus/importfiles/ImportHelper.java [hunk 2]
```diff
@@ -534,7 +534,7 @@ private void handleResult(GpxFile result, String name, OnSuccessfulGpxImport onG
 					if (AndroidUtils.isActivityNotDestroyed(activity)) {
 						FragmentManager manager = activity.getSupportFragmentManager();
 						ImportTracksFragment.showInstance(manager, result, name,
-								destinationDir.getAbsolutePath(), gpxImportListener, fileSize);
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/importfiles/ImportHelper.java:537]: Why do we replace fileSize with selectedTracks.size()?
