### PR TITLE
fix missing inset on add view

### LINKED ISSUE #24351: Missing insets
### Maps & Resources
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td> </td>
    <td> </td>
  </tr>
</table>   
</details>  

- [x] Bottom inset in Maps & Resources
- [x] Left / Right inset  in Maps & Resources

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td> </td>
        <td> </td>
      </tr>
    </table>   
</details>   

- [x] Search results are not visible 

- - - - - -
 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td> </td>
      </tr>
    </table>
</details>  

- [x] Left / Right inset in Builds Landscape

- - - - - -
 
### Context menu

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td> </td>
      </tr>
    </table>
</details>  

- [x] Top inset is missing for Popular place description

- - - - - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td> </td>
      </tr>
    </table>
</details>  

- [x] Unable to rich Coordinates, on this place for example https://osmand.net/map/poi/?pin=52.36560%2C4.89901&name=Willet-Holthuysen&type=Museum#15/52.36560/4.89901

- - - - - -
 
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td> </td>
      </tr>
    </table>
</details>  

- [x] Add Waypoint, add background below navigation bar

### PR DESCRIPTION
**Pull request by 0xRe1nk0**

### CODE REVIEW

File: OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java [hunk 1]
```diff
@@ -278,6 +278,13 @@ public void setMapContextMenu(@Nullable MapContextMenu mapContextMenu) {
 		this.mapContextMenu = mapContextMenu;
 	}
 
+	protected void requestMenuRelayout(@NonNull View anchor) {
+		MapContextMenu mapContextMenu = getMapContextMenu();
+		if (!isHidden() && mapContextMenu != null) {
+			anchor.post(mapContextMenu::updateLayout);
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/mapcontextmenu/MenuBuilder.java]: Can mapContextMenu become hidden before runnable is triggered?
