### PR TITLE
fix #21946 disappearing track on change color type

### LINKED ISSUE #21946: `Road type` & `Surface` can't apply to GPX
### Description

There are several issues here:
1. Road type & Surface are displayed in solid color on the screen (sometimes they are displayed empty)
2. Road type & Surface are not applied to the track after saving the settings on the custom screen and going to the map

### Steps to reproduce

Menu > Plan a route >  Create new route > Save > Open gpx > Appearance > Colour > Road type or Surface > Apply

### Actual result

<details><summary></summary>
<table style="width:100%">
  <tr>
    <th>1</th>
    <th>2</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/user-attachments/assets/78f154f3-1df6-4492-80b5-bf0a5a5dfda7
"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/user-attachments/assets/839df0b8-5898-4cbc-9c23-d3712583ac8f
"  width="300" height="auto"/> </td>
  </tr>
</table> </details>

### Expected result

<details><summary>Color types are displayed in the preview screen and after saving the settings</summary>
<video src="https://github.com/user-attachments/assets/929b838c-7c97-43cb-aa17-8e551fcbad9b"></video>
</details>

### Your Environment
OsmAnd Version: OsmAnd~ 5.0.0#4433m, Released: 2025-02-21

### PR DESCRIPTION
**Pull request by 0xRe1nk0**

### CODE REVIEW

File: OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java [hunk 1]
```diff
@@ -1237,6 +1237,7 @@ private void drawSelectedFileSegments(SelectedGpxFile selectedGpxFile, boolean c
 					geometryWay.vectorLineArrowsProvider = renderableSegment.getGeometryWay().vectorLineArrowsProvider;
 					geometryWay.updateCustomWidth(renderableSegment.getGeometryWay().getCustomWidth());
 					geometryWay.updateDrawDirectionArrows(renderableSegment.getGeometryWay().getDrawDirectionArrows());
+					resetSymbolProviders(oldSegments.get(0));
```
Comment (alex-osm) [inline OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java:1240]: Looks wrong. It is related to current recording track.

Comment (Chumva) [reply OsmAnd/src/net/osmand/plus/views/layers/GPXLayer.java]: Improved check for CurrentTrack instead of RenderableSegment should fix the issue. It happened due to calling oldSegments.remove(0); for StandardTracks
