### PR TITLE
Fix #12970 Wrong Street Name suggested

### LINKED ISSUE #12970: Wrong Street Name suggested for Location or Favorites Name, Maybe map issue?
### Description
Wrong Street Name suggested for Location or Favorites Name. Maybe map issue?

### How to reproduce?

Press map, see Location shown is not from nearby street, but from street some km away.
Examples:
35.29215, -80.65122
anywhere from there along Rocky River Road eastward to:
35.29533, -80.63452

### Your Environment
OsmAnd Version: OsmAnd~ 4.0.7, from F-Droid Sept. 8, 2021
Android/iOS version: 11 (LineageOS fork, without gapps, no address lookup backend active)
Device model: Nexus 6

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.
 Offline. North Carolina USA, August 31, 2021

### PR DESCRIPTION
**Pull request by Dima-1**

### CODE REVIEW

File: OsmAnd-java/src/main/java/net/osmand/binary/GeocodingUtilities.java [hunk 1]
```diff
@@ -146,7 +146,7 @@ public String toString() {
 		List<GeocodingResult> lst = new ArrayList<GeocodingUtilities.GeocodingResult>();
 		List<RouteSegmentPoint> listR = new ArrayList<BinaryRoutePlanner.RouteSegmentPoint>();
 		// we allow duplications to search in both files for boundary regions 
-		rp.findRouteSegment(lat, lon, ctx, listR, false, true);
+		rp.findRouteSegment(lat, lon, ctx, listR, true, true);
```
Comment (vshcherb) [inline OsmAnd-java/src/main/java/net/osmand/binary/GeocodingUtilities.java:149]: this parameter transportStop = true ? why do we need it ?

Comment (Dima-1) [reply OsmAnd-java/src/main/java/net/osmand/binary/GeocodingUtilities.java:149]: It necessary in order to avoid add GPS_POSSIBLE_ERROR in the https://github.com/osmandapp/OsmAnd/blob/3d62dd2fba4207a6255632e0e755cedd92a2e4b8/OsmAnd-java/src/main/java/net/osmand/router/RoutePlannerFrontEnd.java#L177
