### PR TITLE
Fix #20422

### LINKED ISSUE #20422: Make Premature rotation of map during navigation optional
### Description

With reference to ticket 19706, the opposite is now happening. The cursor correctly follows the route line, now it is the map that rotates incorrectly before intersections, roundabouts or other intersections of roads. The thing is very, very annoying 

### Actual result

Not correct

### Expected result

The map must work as in the version of 07/05/2024 4.7.17 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

### PR DESCRIPTION
**Pull request by Chumva**

### CODE REVIEW

File: OsmAnd/src/net/osmand/plus/routing/RoutingHelperUtils.java [hunk 1]
```diff
@@ -125,10 +126,14 @@ public static void approximateBearingIfNeeded(@NonNull RoutingHelper routingHelp
 				previousRouteLocation.getLatitude(), previousRouteLocation.getLongitude(),
 				currentRouteLocation.getLatitude(), currentRouteLocation.getLongitude());
 		float currentSegmentBearing = MapUtils.normalizeDegrees360(previousRouteLocation.bearingTo(currentRouteLocation));
-		float nextSegmentBearing = MapUtils.normalizeDegrees360(currentRouteLocation.bearingTo(nextRouteLocation));
-		float segmentsBearingDelta = MapUtils.unifyRotationDiff(currentSegmentBearing, nextSegmentBearing)
-				* projectionOffsetN * projectionOffsetN;
-		float approximatedBearing = MapUtils.normalizeDegrees360(currentSegmentBearing + segmentsBearingDelta);
+
+		float approximatedBearing = currentSegmentBearing;
+		if (previewNextTurn) {
```
Comment (vshcherb) [inline OsmAnd/src/net/osmand/plus/routing/RoutingHelperUtils.java:131]: Preview next turn shouldn't affect bearing!
