### PR TITLE
Fix #18342

### LINKED ISSUE #18342: Add support for tags: author, cmt, link, keywords, copyright, email
### Description

No matter how I import a gpx file into OsmAnd, I am not able to leverage the <url> or <urlname> tags if they are present. As far as I understand, OsmAnd even drops this information when importing the GPX.

But url and urlname are part of the standard specification of gpx, so I think they should really be supported natively. And as the user of #14618 wrote: A link "can allow the user to open the link retrieving more information about this point and maybe adding some custom workflow (for example triggering a web page with more information and logic regarding the reached point)"

### Steps to reproduce

Create a simple gpx file like this:
```
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?><gpx version="1.1" creator="Mundraub2Use Script" xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
<name>Rider Houses</name>
<wpt lat="43.94073" lon="141.650913">
<name>Rider House 346</name>
<url>https://www.hatinosu.net/house/archives/346</url>
<urlname>Rider House 346</urlname>
</wpt>
<wpt lat="43.322306" lon="145.632708">
<name>Rider House 349</name>
<url>https://www.hatinosu.net/house/archives/349</url>
<urlname>Rider House 349</urlname>
</wpt>
</gpx>
```

Import it into OsmAnd and see how url is drop, by opening the imported file. Or put the file into the tracks folder of OsmAnd and see how no url information is available when selection the waypoints in the map.

### Actual result

No url anywhere.

### Expected result

Somehow the url should be displayed and also not be deleted from the gpx.

### Your Environment (required)

```
OsmAnd Version: 4.5.10
Android/iOS version: 9
Device model: Sansung S8
```

### PR DESCRIPTION
**Pull request by 0xRe1nk0**

### CODE REVIEW

File: OsmAnd-java/src/main/java/net/osmand/gpx/GPXUtilities.java [hunk 1]
```diff
@@ -1753,6 +1753,19 @@ public static GPXFile loadGPXFile(InputStream stream, GPXExtensionsReader extens
...
+						String text = parser.getText();
+						if(((Author) parse).name == null){
+							((Author) parse).name = text;
+						}
+					} else if (parse instanceof Copyright) {
+						String text = parser.getText();
+						if (((Copyright) parse).author == null) {
+							((Copyright) parse).author = text;
+						}
+					}
```
Comment (alex-osm) [inline OsmAnd-java/src/main/java/net/osmand/gpx/GPXUtilities.java:1768]: Looks wrong. Does not conform to https://www.topografix.com/GPX/1/1/#type_metadataType

File: OsmAnd/src/net/osmand/data/FavouritePoint.java [hunk 2]
```diff
@@ -38,6 +38,7 @@ public class FavouritePoint implements Serializable, LocationPoint {
 	private String description;
 	private String address;
 	private String comment;
+	private String link;
```
Comment (alex-osm) [inline OsmAnd/src/net/osmand/data/FavouritePoint.java:41]: Do we need link for fav?

File: OsmAnd/src/net/osmand/data/FavouritePoint.java [hunk 3]
```diff
@@ -311,6 +313,14 @@ public void setDescription(String description) {
 		this.description = description;
 	}
 
+	public String getLink() {
```
Comment (alex-osm) [inline OsmAnd/src/net/osmand/data/FavouritePoint.java:316]: Why `getLink` is not used in `toWpt()`?

File: OsmAnd/src/net/osmand/plus/track/cards/AuthorCard.java [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+	@Override
+	public int getCardLayoutId() {
+		return R.layout.author_card;
+	}
+
+	@Override
+	public void updateContent() {
+		GPXUtilities.Author author = gpxFile.metadata.author;
+
+		String name = author.name;
```
Comment (alex-osm) [inline OsmAnd/src/net/osmand/plus/track/cards/AuthorCard.java:49]: `metadata.author` is null by default

File: OsmAnd/src/net/osmand/plus/track/cards/CopyrightCard.java [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+	@Override
+	public int getCardLayoutId() {
+		return R.layout.copyright_card;
+	}
+
+	@Override
+	public void updateContent() {
+		GPXUtilities.Copyright copyright = gpxFile.metadata.copyright;
+
+		String author = copyright.author;
```
Comment (alex-osm) [inline OsmAnd/src/net/osmand/plus/track/cards/CopyrightCard.java:37]: `metadata.copyright` might be null

File: OsmAnd/src/net/osmand/plus/track/cards/ExtensionsCard.java [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+	}
+
+	@Override
+	public int getCardLayoutId() {
+		return R.layout.extensions_card;
+	}
+
+	@Override
+	public void updateContent() {
+		Map<String, String> extensions = gpxFile.metadata.extensions;
```
Comment (alex-osm) [inline OsmAnd/src/net/osmand/plus/track/cards/ExtensionsCard.java:38]: Possible NPE?

File: OsmAnd/src/net/osmand/plus/track/cards/ExtensionsCard.java [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+import net.osmand.gpx.GPXFile;
+import net.osmand.plus.OsmandApplication;
+import net.osmand.plus.R;
+import net.osmand.plus.activities.MapActivity;
+import net.osmand.plus.routepreparationmenu.cards.MapBaseCard;
+import net.osmand.util.Algorithms;
+
+import java.util.Map;
+
+public class ExtensionsCard extends MapBaseCard {
```
Comment (alex-osm) [inline OsmAnd/src/net/osmand/plus/track/cards/ExtensionsCard.java:21]: MetadataExtensionsCard?

File: OsmAnd/res/layout/gpx_info_card.xml [hunk 8]
```diff
@@ -51,8 +50,16 @@
...
+		<include
+			android:id="@+id/link_container"
+			layout="@layout/item_with_title_desc"
+			android:visibility="gone" />
 
-	<include layout="@layout/card_bottom_divider" />
+		<include
+			android:id="@+id/description_container"
+			layout="@layout/item_with_title_desc"
+			android:visibility="gone" />
```
Comment (Chumva) [inline OsmAnd/res/layout/gpx_info_card.xml:61]: It is better to control visibility in code, also we can inflate necessary items in card

File: OsmAnd/src/net/osmand/plus/track/cards/AuthorCard.java [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+		String email = author.email;
+		String link = author.link;
+
+		updateVisibility(!Algorithms.isEmpty(name) || !Algorithms.isEmpty(email) || !Algorithms.isEmpty(link));
+		OsmandApplication app = mapActivity.getMyApplication();
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/track/cards/AuthorCard.java:54]: We already have app in base class

File: OsmAnd/src/net/osmand/plus/track/cards/ExtensionsCard.java [hunk 10]
```diff
@@ -0,0 +1,49 @@
...
+	private final GPXFile gpxFile;
+	private final boolean nightMode;
+
+	public ExtensionsCard(@NonNull MapActivity mapActivity, @NonNull GPXFile gpxFile, boolean nightMode) {
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/track/cards/ExtensionsCard.java:25]: Probably we can pass Metadata instead of gpx in these new cards

File: OsmAnd/src/net/osmand/plus/track/cards/ExtensionsCard.java [hunk 11]
```diff
@@ -0,0 +1,49 @@
...
+
+	@Override
+	public void updateContent() {
+		Map<String, String> extensions = gpxFile.metadata.extensions;
+		updateVisibility(!Algorithms.isEmpty(extensions));
+		ViewGroup container = view.findViewById(R.id.extensions_container);
+		OsmandApplication app = mapActivity.getMyApplication();
+
+		for (String key : extensions.keySet()) {
+			LinearLayout extensionView = (LinearLayout) LayoutInflater.from(view.getContext()).inflate(R.layout.item_with_title_desc, null);
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/track/cards/ExtensionsCard.java:44]: we have themed inflater in base class

File: OsmAnd/src/net/osmand/plus/track/cards/AuthorCard.java [hunk 12]
```diff
@@ -0,0 +1,116 @@
...
+import net.osmand.plus.mapcontextmenu.other.ShareMenu;
+import net.osmand.plus.routepreparationmenu.cards.MapBaseCard;
+import net.osmand.plus.utils.AndroidUtils;
+import net.osmand.util.Algorithms;
+
+public class AuthorCard extends MapBaseCard {
+	public static final int NO_ICON = -1;
+
+	private final GPXFile gpxFile;
+	private final boolean nightMode;
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/track/cards/AuthorCard.java:32]: we have nightMode in base class, which is [initialized in constructor](https://github.com/osmandapp/Osmand/blob/6f4ba1a7e1025b35cf5b2ebda5e6dc4ea97a9635/OsmAnd/src/net/osmand/plus/routepreparationmenu/cards/BaseCard.java#L61). It is better to avoid duplicating class variables in subclasses
