### PR TITLE
fix #22666

### LINKED ISSUE #22666: Text crop, empty second line on Next turn widget
### How to reproduce
* Build route https://osmand.net/map?start=52.228157%2C21.141283&end=52.286449%2C21.141426&profile=car#13/52.228140/21.103629

### Actual result

<table style="width:100%">
  <tr>
    <th>Route details</th>
    <th>1</th>
    <th>2</th>
    <th>3</th>
  </tr>
  <tr>
    <td> </td>
    <td> </td>
    <td> </td>
    <td> </td>
  </tr>
</table>  

1. Text cropped, but full line is empty `Płowiec...` 
2. Excessive padding between distance and units on the first line `15  m`
3. Empty instructions both in Route details and Widget
4. Probably we should add commas instead of cropped words: `Take 1 exit and go Marsa towards Nowy Dwór Mazowiecki, Wegrów, Rembertów `
* * Now `Marsa  Nowy Dwór Mazowiecki` > `Marsa, Nowy Dwór Mazowiecki`

### Expected result

**Environment**
OsmAnd Version: 5.0
Android: 16 Beta
Device model: Google Pixel 6A

### PR DESCRIPTION
**Pull request by 0xRe1nk0**
-fix text crop/excessive padding
-use turn type instruction instead empty route description -fix additional empty space

### CODE REVIEW

File: OsmAnd/src/net/osmand/plus/views/mapwidgets/OutlinedTextContainer.java [hunk 1]
```diff
@@ -175,6 +175,9 @@ private TextView createTextView(int type) {
 	public void setText(@Nullable CharSequence text) {
 		outlineTextView.setText(text);
 		mainTextView.setText(text);
+
+		outlineTextView.requestLayout();
+		mainTextView.requestLayout();
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/views/mapwidgets/OutlinedTextContainer.java:180]: Why do we need here additional requestLayout() ? setText cannot update textView?

File: OsmAnd/src/net/osmand/plus/routing/RouteDirectionInfo.java [hunk 2]
```diff
@@ -71,7 +71,15 @@ public String getDescriptionRoute(OsmandApplication ctx, int collectedDistance)
...
-		return descriptionRoute;
+		return getDescriptionRoutePart(false);
+	}
+
+	public String getDescriptionRoutePart(boolean forceTurnType) {
+		if (forceTurnType) {
+			return !Algorithms.isEmpty(descriptionRoute) ? descriptionRoute : turnType.toString();
+		} else {
+			return descriptionRoute;
+		}
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/routing/RouteDirectionInfo.java]: can be simplified
