### PR TITLE
Try to fix #16818

### LINKED ISSUE #16818: Wikipedia POI continue to be displayed after the plugin is disabled
### Description
Wikipedia POI continues to be displayed after the plugin is disabled

### Steps to reproduce

- Menu
- Plugins
- Wikipedia
- Enable
- Configure map
- Wikipedia POI
- Enable
- Menu
- Plugins
- Wikipedia
- Disable
- Back to map

### Actual result
Wikipedia POI continues to be displayed

https://user-images.githubusercontent.com/104760013/227979574-4b6ff0ca-6c5b-4a0c-9d17-3c80c5ba4739.mp4

### Expected result
Wikipedia POIs disappear after plugin deactivation

### Your Environment
OsmAnd Version: OsmAnd~ 4.5.0#14272mqta, Released: 2023-03-27
Android/iOS version: Android 12
Device model: Poco x3 nfc

### PR DESCRIPTION
**Pull request by Chumva**

### CODE REVIEW

File: OsmAnd/src/net/osmand/plus/wikipedia/WikipediaPlugin.java [hunk 1]
```diff
@@ -161,6 +161,12 @@ public boolean init(@NonNull OsmandApplication app, Activity activity) {
 		return true;
 	}
 
+	@Override
+	public void disable(@NonNull OsmandApplication app) {
+		super.disable(app);
+		toggleWikipediaPoi(false, null);
```
Comment (Chumva) [inline OsmAnd/src/net/osmand/plus/wikipedia/WikipediaPlugin.java:167]: We have access to WikiPoiFilter in search even if WikipediaPlugin is disabled because it is stored in PoiFiltersHelper.
